
import {ArrowLeft, CheckCircle, Download, FileText, FolderOpen, MousePointer, Settings, Upload} from 'lucide-react';
import {pagePaths} from "@/path-routes";
import Link from "next/link";
import {appName} from "@/constants";

export const metadata = {
    title: `TSV Export | ${appName}`,
};

const TSVImportGuide = () => {
    return (
        <div
            className="bg-gradient-to-br from-green-50 via-white to-emerald-50 dark:from-gray-900 dark:via-gray-800 dark:to-green-900/20">
            <div className="w-8/12 mx-auto px-6 py-12">
                {/* Header */}
                <div className="text-center mb-12">
                    <Link href={pagePaths.getAppGuidePage()}>

                        <button
                            className="inline-flex items-center text-green-600 dark:text-green-400 hover:text-green-700 dark:hover:text-green-300 mb-6 transition-colors">
                            <ArrowLeft className="w-4 h-4 mr-2"/>
                            Back to options
                        </button>
                    </Link>
                    <div className="flex justify-center mb-6">
                        <div className="relative">
                            <div
                                className="w-20 h-20 bg-gradient-to-br from-green-500 to-emerald-600 rounded-2xl flex items-center justify-center shadow-lg">
                                <FileText className="w-10 h-10 text-white"/>
                            </div>
                            <div
                                className="absolute -bottom-2 -right-2 w-8 h-8 bg-blue-500 rounded-full flex items-center justify-center shadow-md">
                                <Download className="w-5 h-5 text-white"/>
                            </div>
                        </div>
                    </div>

                    <h1 className="text-4xl font-bold bg-gradient-to-r from-green-600 to-emerald-600 bg-clip-text text-transparent mb-4">
                        Import TSV to Anki
                    </h1>
                    <p className="text-xl text-gray-600 dark:text-gray-300 max-w-2xl mx-auto">
                        Export your flashcards as a TSV file and import them manually into Anki for full control over
                        your deck
                    </p>
                </div>

                {/* Step 1: Export from App */}
                <div
                    className={`bg-white dark:bg-gray-800 rounded-2xl shadow-xl dark:shadow-gray-900/20 p-8 mb-8 border border-gray-100 dark:border-gray-700 transition-all duration-300`}>
                    <div className="flex items-center mb-6">
                        <div
                            className="w-12 h-12 bg-gradient-to-br from-blue-500 to-indigo-600 text-white rounded-xl flex items-center justify-center text-lg font-bold shadow-lg">
                            1
                        </div>
                        <div className="ml-4">
                            <h2 className="text-2xl font-bold text-gray-900 dark:text-white">Export from Your App</h2>
                            <p className="text-gray-600 dark:text-gray-300">Download your flashcards as a TSV file</p>
                        </div>
                    </div>

                    <div className="space-y-6">
                        <div
                            className="bg-blue-50 dark:bg-blue-900/20 rounded-xl p-6 border border-blue-200 dark:border-blue-800/30">
                            <h3 className="font-semibold text-blue-900 dark:text-blue-100 mb-4 flex items-center">
                                <Download className="w-5 h-5 mr-2"/>
                                Export Process
                            </h3>
                            <ol className="space-y-4">
                                <li className="flex items-start">
                                    <span
                                        className="bg-blue-600 text-white rounded-full w-8 h-8 flex items-center justify-center text-sm font-semibold mr-4 mt-0.5 flex-shrink-0">1</span>
                                    <div>
                                        <span className="text-blue-800 dark:text-blue-200 font-medium">Navigate to your flashcards review page</span>
                                        <p className="text-blue-700 dark:text-blue-300 text-sm mt-1">Go to the section
                                            where you can review all cards generated by AI</p>
                                    </div>
                                </li>
                                <li className="flex items-start">
                                    <span
                                        className="bg-blue-600 text-white rounded-full w-8 h-8 flex items-center justify-center text-sm font-semibold mr-4 mt-0.5 flex-shrink-0">2</span>
                                    <div>
                                        <span className="text-blue-800 dark:text-blue-200 font-medium">Click the "Export to file" button</span>
                                        <p className="text-blue-700 dark:text-blue-300 text-sm mt-1">Look for the export
                                            button, located on top of the flashcards list</p>
                                    </div>
                                </li>
                                <li className="flex items-start">
                                    <span
                                        className="bg-blue-600 text-white rounded-full w-8 h-8 flex items-center justify-center text-sm font-semibold mr-4 mt-0.5 flex-shrink-0">3</span>
                                    <div>
                                        <span className="text-blue-800 dark:text-blue-200 font-medium">Download will start automatically</span>
                                        <p className="text-blue-700 dark:text-blue-300 text-sm mt-1">Your browser will
                                            download a .tsv file containing all your flashcard data</p>
                                    </div>
                                </li>
                            </ol>
                        </div>

                        <div
                            className="bg-amber-50 dark:bg-amber-900/20 rounded-xl p-6 border border-amber-200 dark:border-amber-800/30">
                            <div className="flex items-start">
                                <FileText
                                    className="w-5 h-5 text-amber-600 dark:text-amber-400 mr-3 mt-0.5 flex-shrink-0"/>
                                <div>
                                    <h4 className="font-semibold text-amber-900 dark:text-amber-100 mb-2">About TSV
                                        Files</h4>
                                    <p className="text-amber-800 dark:text-amber-200 text-sm">
                                        TSV (Tab-Separated Values) files are similar to CSV files but use tabs instead
                                        of commas to separate data.
                                        This format is perfect for Anki imports as it preserves formatting and handles
                                        special characters better.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                {/* Step 2: Open Anki Import */}
                <div
                    className={`bg-white dark:bg-gray-800 rounded-2xl shadow-xl dark:shadow-gray-900/20 p-8 mb-8 border border-gray-100 dark:border-gray-700 transition-all duration-300`}>
                    <div className="flex items-center mb-6">
                        <div
                            className="w-12 h-12 bg-gradient-to-br from-green-500 to-emerald-600 text-white rounded-xl flex items-center justify-center text-lg font-bold shadow-lg">
                            2
                        </div>
                        <div className="ml-4">
                            <h2 className="text-2xl font-bold text-gray-900 dark:text-white">Open Anki Import</h2>
                            <p className="text-gray-600 dark:text-gray-300">Access the import feature in Anki</p>
                        </div>
                    </div>

                    <div className="space-y-6">
                        <div
                            className="bg-green-50 dark:bg-green-900/20 rounded-xl p-6 border border-green-200 dark:border-green-800/30">
                            <h3 className="font-semibold text-green-900 dark:text-green-100 mb-4 flex items-center">
                                <FolderOpen className="w-5 h-5 mr-2"/>
                                Opening the Import Dialog
                            </h3>
                            <ol className="space-y-4">
                                <li className="flex items-start">
                                    <span
                                        className="bg-green-600 text-white rounded-full w-8 h-8 flex items-center justify-center text-sm font-semibold mr-4 mt-0.5 flex-shrink-0">1</span>
                                    <div>
                                        <span className="text-green-800 dark:text-green-200 font-medium">Open Anki desktop application</span>
                                        <p className="text-green-700 dark:text-green-300 text-sm mt-1">Make sure Anki is
                                            running and you can see your main deck screen</p>
                                    </div>
                                </li>
                                <li className="flex items-start">
                                    <span
                                        className="bg-green-600 text-white rounded-full w-8 h-8 flex items-center justify-center text-sm font-semibold mr-4 mt-0.5 flex-shrink-0">2</span>
                                    <div>
                                        <span className="text-green-800 dark:text-green-200 font-medium">Navigate to File → Import</span>
                                        <p className="text-green-700 dark:text-green-300 text-sm mt-1">Click on the
                                            "File" menu in the top menu bar, then select "Import"</p>
                                    </div>
                                </li>
                                <li className="flex items-start">
                                    <span
                                        className="bg-green-600 text-white rounded-full w-8 h-8 flex items-center justify-center text-sm font-semibold mr-4 mt-0.5 flex-shrink-0">3</span>
                                    <div>
                                        <span className="text-green-800 dark:text-green-200 font-medium">Select your TSV file</span>
                                        <p className="text-green-700 dark:text-green-300 text-sm mt-1">Browse to your
                                            Downloads folder and select the .tsv file you just exported</p>
                                    </div>
                                </li>
                            </ol>
                        </div>

                        <div className="grid md:grid-cols-2 gap-6">
                            <div
                                className="bg-gray-50 dark:bg-gray-700/50 rounded-xl p-6 border border-gray-200 dark:border-gray-600">
                                <h4 className="font-semibold text-gray-900 dark:text-gray-100 mb-3">Alternative
                                    Method</h4>
                                <p className="text-gray-700 dark:text-gray-300 text-sm mb-3">
                                    You can also drag and drop the TSV file directly onto the Anki window to start the
                                    import process.
                                </p>
                                <div className="flex items-center text-gray-600 dark:text-gray-400 text-sm">
                                    <MousePointer className="w-4 h-4 mr-2"/>
                                    <span>Drag & Drop supported</span>
                                </div>
                            </div>

                            <div
                                className="bg-blue-50 dark:bg-blue-900/20 rounded-xl p-6 border border-blue-200 dark:border-blue-800/30">
                                <h4 className="font-semibold text-blue-900 dark:text-blue-100 mb-3">Quick Tip</h4>
                                <p className="text-blue-800 dark:text-blue-200 text-sm">
                                    Keep your TSV file in an easy-to-find location like your Desktop or Downloads folder
                                    for quick access.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>

                {/* Step 3: Configure Settings */}
                <div
                    className={`bg-white dark:bg-gray-800 rounded-2xl shadow-xl dark:shadow-gray-900/20 p-8 mb-8 border border-gray-100 dark:border-gray-700 transition-all duration-300 }`}>
                    <div className="flex items-center mb-6">
                        <div
                            className="w-12 h-12 bg-gradient-to-br from-purple-500 to-violet-600 text-white rounded-xl flex items-center justify-center text-lg font-bold shadow-lg">
                            3
                        </div>
                        <div className="ml-4">
                            <h2 className="text-2xl font-bold text-gray-900 dark:text-white">Configure Import
                                Settings</h2>
                            <p className="text-gray-600 dark:text-gray-300">Set the correct field separator for TSV
                                format</p>
                        </div>
                    </div>

                    <div className="space-y-6">
                        <div
                            className="bg-purple-50 dark:bg-purple-900/20 rounded-xl p-6 border border-purple-200 dark:border-purple-800/30">
                            <h3 className="font-semibold text-purple-900 dark:text-purple-100 mb-4 flex items-center">
                                <Settings className="w-5 h-5 mr-2"/>
                                Critical Setting: Field Separator
                            </h3>

                            <div
                                className="bg-red-50 dark:bg-red-900/20 rounded-lg p-4 mb-4 border border-red-200 dark:border-red-800/30">
                                <div className="flex items-start">
                                    <div
                                        className="bg-red-500 text-white rounded-full w-6 h-6 flex items-center justify-center text-sm font-bold mr-3 mt-0.5 flex-shrink-0">!
                                    </div>
                                    <div>
                                        <h4 className="font-semibold text-red-900 dark:text-red-100 mb-1">Important!</h4>
                                        <p className="text-red-800 dark:text-red-200 text-sm">
                                            You must change the "Fields separated by" setting
                                            to <strong>"Tab"</strong> for TSV files to import correctly.
                                        </p>
                                    </div>
                                </div>
                            </div>

                            <ol className="space-y-4">
                                <li className="flex items-start">
                                    <span
                                        className="bg-purple-600 text-white rounded-full w-8 h-8 flex items-center justify-center text-sm font-semibold mr-4 mt-0.5 flex-shrink-0">1</span>
                                    <div>
                                        <span className="text-purple-800 dark:text-purple-200 font-medium">Look for "Fields separated by" option</span>
                                        <p className="text-purple-700 dark:text-purple-300 text-sm mt-1">This setting is
                                            usually located in the import dialog window</p>
                                    </div>
                                </li>
                                <li className="flex items-start">
                                    <span
                                        className="bg-purple-600 text-white rounded-full w-8 h-8 flex items-center justify-center text-sm font-semibold mr-4 mt-0.5 flex-shrink-0">2</span>
                                    <div>
                                        <span className="text-purple-800 dark:text-purple-200 font-medium">Change from "Comma" to "Tab"</span>
                                        <p className="text-purple-700 dark:text-purple-300 text-sm mt-1">Click the
                                            dropdown and select "Tab" as the field separator</p>
                                    </div>
                                </li>
                                <li className="flex items-start">
                                    <span
                                        className="bg-purple-600 text-white rounded-full w-8 h-8 flex items-center justify-center text-sm font-semibold mr-4 mt-0.5 flex-shrink-0">3</span>
                                    <div>
                                        <span className="text-purple-800 dark:text-purple-200 font-medium">Verify the preview looks correct</span>
                                        <p className="text-purple-700 dark:text-purple-300 text-sm mt-1">You should see
                                            your flashcard content properly separated in columns</p>
                                    </div>
                                </li>
                            </ol>
                        </div>

                        <div className="bg-gradient-to-r from-purple-500 to-violet-600 rounded-xl p-6 text-white">
                            <div className="flex items-center mb-4">
                                <div className="bg-white/20 rounded-lg p-2 mr-3">
                                    <Settings className="w-6 h-6"/>
                                </div>
                                <h4 className="font-semibold text-lg">Visual Guide</h4>
                            </div>
                            <div className="bg-white/10 rounded-lg p-4">
                                <p className="text-purple-100 text-sm mb-2">What you should see:</p>
                                <div className="font-mono text-sm bg-white/20 rounded p-2">
                                    <div className="text-purple-100">Fields separated by: <span
                                        className="bg-white/30 px-2 py-1 rounded">Tab</span></div>
                                </div>
                            </div>
                        </div>

                        <div className="grid md:grid-cols-2 gap-6">
                            <div
                                className="bg-green-50 dark:bg-green-900/20 rounded-xl p-6 border border-green-200 dark:border-green-800/30">
                                <h4 className="font-semibold text-green-900 dark:text-green-100 mb-3 flex items-center">
                                    <CheckCircle className="w-4 h-4 mr-2"/>
                                    Correct Setting
                                </h4>
                                <p className="text-green-800 dark:text-green-200 text-sm">
                                    When set to "Tab", your flashcard front and back will appear in separate, properly
                                    aligned columns.
                                </p>
                            </div>

                            <div
                                className="bg-red-50 dark:bg-red-900/20 rounded-xl p-6 border border-red-200 dark:border-red-800/30">
                                <h4 className="font-semibold text-red-900 dark:text-red-100 mb-3">❌ Wrong Setting</h4>
                                <p className="text-red-800 dark:text-red-200 text-sm">
                                    If left on "Comma", your flashcard content will appear jumbled together in a single
                                    column.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>

                {/* Step 4: Complete Import */}
                <div
                    className={`bg-white dark:bg-gray-800 rounded-2xl shadow-xl dark:shadow-gray-900/20 p-8 mb-8 border border-gray-100 dark:border-gray-700 transition-all duration-300`}>
                    <div className="flex items-center mb-6">
                        <div
                            className="w-12 h-12 bg-gradient-to-br from-emerald-500 to-teal-600 text-white rounded-xl flex items-center justify-center text-lg font-bold shadow-lg">
                            4
                        </div>
                        <div className="ml-4">
                            <h2 className="text-2xl font-bold text-gray-900 dark:text-white">Complete the Import</h2>
                            <p className="text-gray-600 dark:text-gray-300">Finalize and start using your flashcards</p>
                        </div>
                    </div>

                    <div className="space-y-6">
                        <div
                            className="bg-emerald-50 dark:bg-emerald-900/20 rounded-xl p-6 border border-emerald-200 dark:border-emerald-800/30">
                            <h3 className="font-semibold text-emerald-900 dark:text-emerald-100 mb-4 flex items-center">
                                <Upload className="w-5 h-5 mr-2"/>
                                Final Steps
                            </h3>
                            <ol className="space-y-4">
                                <li className="flex items-start">
                                    <span
                                        className="bg-emerald-600 text-white rounded-full w-8 h-8 flex items-center justify-center text-sm font-semibold mr-4 mt-0.5 flex-shrink-0">1</span>
                                    <div>
                                        <span className="text-emerald-800 dark:text-emerald-200 font-medium">Choose or create a deck</span>
                                        <p className="text-emerald-700 dark:text-emerald-300 text-sm mt-1">Select an
                                            existing deck or create a new one for your imported cards</p>
                                    </div>
                                </li>
                                <li className="flex items-start">
                                    <span
                                        className="bg-emerald-600 text-white rounded-full w-8 h-8 flex items-center justify-center text-sm font-semibold mr-4 mt-0.5 flex-shrink-0">2</span>
                                    <div>
                                        <span className="text-emerald-800 dark:text-emerald-200 font-medium">Review other import options</span>
                                        <p className="text-emerald-700 dark:text-emerald-300 text-sm mt-1">Check
                                            settings like "Allow HTML in fields" if your cards contain formatting</p>
                                    </div>
                                </li>
                                <li className="flex items-start">
                                    <span
                                        className="bg-emerald-600 text-white rounded-full w-8 h-8 flex items-center justify-center text-sm font-semibold mr-4 mt-0.5 flex-shrink-0">3</span>
                                    <div>
                                        <span className="text-emerald-800 dark:text-emerald-200 font-medium">Click "Import" to complete</span>
                                        <p className="text-emerald-700 dark:text-emerald-300 text-sm mt-1">Anki will
                                            process and add all your flashcards to the selected deck</p>
                                    </div>
                                </li>
                            </ol>
                        </div>

                        <div
                            className="bg-blue-50 dark:bg-blue-900/20 rounded-xl p-6 border border-blue-200 dark:border-blue-800/30">
                            <h4 className="font-semibold text-blue-900 dark:text-blue-100 mb-3">Optional Settings</h4>
                            <div className="space-y-3">
                                <div className="flex items-center text-blue-800 dark:text-blue-200">
                                    <CheckCircle className="w-4 h-4 mr-3 flex-shrink-0"/>
                                    <span className="text-sm"><strong>Allow HTML in fields:</strong> Enable if your cards have formatting</span>
                                </div>
                                <div className="flex items-center text-blue-800 dark:text-blue-200">
                                    <CheckCircle className="w-4 h-4 mr-3 flex-shrink-0"/>
                                    <span className="text-sm"><strong>Update existing notes:</strong> Choose how to handle duplicates</span>
                                </div>
                                <div className="flex items-center text-blue-800 dark:text-blue-200">
                                    <CheckCircle className="w-4 h-4 mr-3 flex-shrink-0"/>
                                    <span className="text-sm"><strong>Tag imported cards:</strong> Add a tag to identify these cards</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                {/* Success Message */}
                <div
                    className="bg-gradient-to-r from-green-500 to-emerald-600 rounded-2xl p-8 text-center text-white shadow-xl mb-8">
                    <div className="flex justify-center mb-4">
                        <div className="w-16 h-16 bg-white/20 rounded-full flex items-center justify-center">
                            <CheckCircle className="w-8 h-8"/>
                        </div>
                    </div>
                    <h2 className="text-2xl font-bold mb-2">Import Complete!</h2>
                    <p className="text-green-100 mb-6">
                        Your flashcards have been successfully imported into Anki. You can now start studying them in
                        your chosen deck.
                    </p>
                    <Link href={pagePaths.getHomePage()}>
                        <button
                            className="bg-white text-green-600 px-6 py-3 rounded-lg font-semibold hover:bg-green-50 transition-colors shadow-md">
                            Start Studying
                        </button>
                    </Link>
                </div>

                {/* Troubleshooting */}
                <div
                    className="bg-gray-50 dark:bg-gray-800/50 rounded-2xl p-8 border border-gray-200 dark:border-gray-700">
                <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-4">Common Issues & Solutions</h2>
                    <div className="space-y-4">
                        <div className="flex items-start">
                            <div
                                className="bg-amber-500 text-white rounded-full w-6 h-6 flex items-center justify-center text-sm font-bold mr-3 mt-0.5 flex-shrink-0">!
                            </div>
                            <div>
                                <h3 className="font-semibold text-gray-900 dark:text-white text-sm">Cards appear in one
                                    column</h3>
                                <p className="text-gray-600 dark:text-gray-300 text-sm">Make sure "Fields separated by"
                                    is set to "Tab", not "Comma"</p>
                            </div>
                        </div>
                        <div className="flex items-start">
                            <div
                                className="bg-amber-500 text-white rounded-full w-6 h-6 flex items-center justify-center text-sm font-bold mr-3 mt-0.5 flex-shrink-0">!
                            </div>
                            <div>
                                <h3 className="font-semibold text-gray-900 dark:text-white text-sm">Special characters
                                    look wrong</h3>
                                <p className="text-gray-600 dark:text-gray-300 text-sm">Check the encoding setting in
                                    the import dialog (should be UTF-8)</p>
                            </div>
                        </div>
                        <div className="flex items-start">
                            <div
                                className="bg-amber-500 text-white rounded-full w-6 h-6 flex items-center justify-center text-sm font-bold mr-3 mt-0.5 flex-shrink-0">!
                            </div>
                            <div>
                                <h3 className="font-semibold text-gray-900 dark:text-white text-sm">No cards
                                    imported</h3>
                                <p className="text-gray-600 dark:text-gray-300 text-sm">Verify the TSV file isn't empty
                                    and contains the expected data</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default TSVImportGuide;